name: example_one_app
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
